### ISSUE TITLE
Фіксувати військові злочини путінського режиму (фото, відео)

### ISSUE THREAD

**Issue by OlgaBuu** [Amice13/resistinua#3]
**Військові злочини російської армії та їх найманців мають покарані.**

Постраждалі цивільні, нестача необхідного, дитинство в укриттях, розстріли та інші руйнування цивільної інфраструктури,  - усе це має бути зафіксовано та стати доказами в міжнародних судах і трибуналах.

Покарання винних має стати запобіжником від повіторення.

Надислайте фото- і відеодокази на пошту **resistinua@gmail.com**

**ВАЖЛИВО!** Бережіть себе! Не наражайте себе на небезпеку заради фіксації. Здійснюйте фото- і відеофіксацію тільки, коли повністю впевнені в тому, що це не наражає вас на небезпеку.

**Comment by Amice13** [comment]
Додано.
