### ISSUE TITLE
Исправить media.vue

### ISSUE THREAD

**Issue by yharahuts** [Amice13/resistinua#5]
Нужно добавить другие источники для медиа (ОП не только в фб, но и тг, твиттере и веб-сайт), например так: 

![image](https://user-images.githubusercontent.com/2097587/156530395-b4e81e07-61d8-4952-b828-b6ec64da70c4.png)

Если в таком виде верстка норм, я займусь.

**Comment by Amice13** [comment]
Вполне норм. Ссылки в скобочки только возьми.
